databases:
    - name: books
      databaseName: books
      user: books
      plan: free

services:
    - type: web
      name: books
      runtime: ruby
      plan: free
      buildCommand: './bin/render-build.sh'
      startCommand: './bin/rails server'
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: books
                property: connectionString
          - key: RAILS_MASTER_KEY
            sync: false
          - key: WEB_CONCURRENCY
            value: 2 